name: sphinx_gmt
channels:
    - conda-forge
    - defaults
dependencies:
    # Required dependencies
    - pip
    - gmt
    - jinja2
    - sphinx
    # Dev dependencies (general)
    - build
    # Dev dependencies (building documentation)
    - sphinx_rtd_theme
    # Dev dependencies (formatting)
    - black
    - pylint
