name: sphinx_gmt
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - pip
    - gmt
    - jinja2
    - sphinx
    - sphinx_rtd_theme
    - numpydoc
    - build
    - black
    - pylint
