name: sphinx_gmt
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - pip
    - gmt
    - jinja2
    - sphinx=1.8.5
    - sphinx_rtd_theme
    - numpydoc
    - black
    - pylint
